### ISSUE TITLE
Hidden breaking change in v0.8.3

### ISSUE THREAD

**Issue by icebob** [kriszyp/cbor-x#12]
Hi @kriszyp,

Today, I've updated the cbor-x version from 0.8.2 to 0.8.3 in my project and it caused a breaking change because of this commit: https://github.com/kriszyp/cbor-x/commit/b30f65c03fa84575c0f95e6404c15d9f34f94bf7

I could fix it that I set the `useTag259ForMaps: false` to be backwards compatible with 0.8.2.

So I just want to ask that in the future, please increase the major version number (to follow [semver versioning](https://semver.org/)) if the version contains breaking changes. 

Thanks in advance and keep up the good work!

Icebob

**Comment by kriszyp** [comment]
My apologies, I certainly didn't intend to cause a breaking change in a minor/patch version incrementation, I hadn't realized that would break anything, and I definitely (always) intend to try to maintain semver/backcompat (although in my pedantic defense, technically according to the semver spec, with a major version number of 0, there is no guarantee that any version updates are 100% back compatible, but still I do want to try to keep things as stable as possible for everyone, and the only reason I haven't denoted a version of 1.x yet is that I was waiting to see if the CBOR committee was going to accept my record proposal https://github.com/kriszyp/cbor-records that I proposed and use in cbor-x).

Do you think it would be better if this default was changed so that tag 259 is only used for maps when explicitly enabled? Or is this already too late, and if you already fixed/updated this setting? (And referencing #5 , since that is the original ticket for this feature).

**Comment by icebob** [comment]
Thanks. In semver, under 1.0.0 we use the minor version as major and patch as minor. So if the version changed to 0.9.0 I know it should contain breaking changes. So I didn't think about in 0.8.3. But no problem :)

Now I've fixed it with a default `useTag259ForMaps: false` because as I see, it works similarly to 0.8.2.
