### ISSUE TITLE
Add benchmark with Sia

### ISSUE THREAD

**Issue by intech** [kriszyp/cbor-x#24]
Reference https://github.com/pouya-eghbali/sia#performance

**Comment by kriszyp** [comment]
I actually have done some local benchmarking testing Sia against cbor-x/msgpackr. I got mixed results, cbor-x was faster in some situations and Sia in other tests. However, there were a few reasons I didn't publish it. From my testing of the Sia library, I believe it always serializes to the same static buffer, overwriting it each time, which is generally unsafe/unusable for many/most serialization purposes (for example, if you serialize data, and write it to a stream, and do another serialization before the stream's buffers are processed, you can lose data). This approach is, of course, faster, and can be used in certain situations (where you know the serialized data will be "used" before the next serialization call), but doesn't seem like it is a realistic general purpose serialization library, in the same category as other general purpose serializers like cbor-x. And, I am not aware of any widespread adoption of Sia, I believe it is only implemented in a single JS library. And I certainly don't have aspirations of trying to benchmark cbor-x against every library out there, mainly against common libraries with reasonably standardized/adopted serialization formats.

Anyway, Sia certainly does look interesting and has some cool ideas in it (like utfz), and I am quite delighted that its design/optimizations were actually heavily based on cbor-x (https://pouyae.medium.com/sia-an-ultra-fast-serializer-in-pure-javascript-394a5c2166b8). And I can see if I can dig up the benchmarking I had previously done. But again, in my testing, the main situations where Sia could outperform cbor-x seemed to be due to the optimization of writing to a single static buffer (although it is possible I misunderstood how it was working, or the library has changed since then), and I didn't really consider that to be a fair comparison for general purpose serialization.

**Comment by intech** [comment]
@kriszyp thank you for your detailed answer! It was educational for me.
I also looked at Sia earlier and since that time it has not changed, this is confirmed by the history of commits.
