### ISSUE TITLE
Canonical CBOR encoding

### ISSUE THREAD

**Issue by JonasKruckenberg** [kriszyp/cbor-x#4]
Hey! 
This speed at which this library encodes is just marvelous, awesome project!
I noticed however, that this speed comes at the cost of binary size, since for simple "tags" cbor-x doesn't always choose the shortest possible, e.g.
```js
encode(Buffer.alloc(0)) // returns <Buffer 58 00>
```
while other implementations return the shorter (and [canonical](https://datatracker.ietf.org/doc/html/rfc7049#section-3.9)) `<Buffer 40>`.
I would love for this to be corrected, cbor-x is just too fast! 😃 But I can totally understand if this is something that's been done for speed's sake or would require major effort.

**Comment by kriszyp** [comment]
No, this is super easy, just an oversight. Should be fixed with the commit above. I'll get a new version published soon.

**Comment by kriszyp** [comment]
I think I interpreted this about to be just about the byte strings (buffers), which is what the fix addresses. But perhaps this is also about the encoding of the major types, so I'll expand on this to describe their encoding. For all integers (positive and negative), text strings, arrays, and tags (and now byte strings with this fix) we always use the "preferred serialization" (the latest RFC uses this term instead of "canonical") and encode with the one byte tokens when possible. For JS objects that are serialized to maps (not using the record tags/options), by default these are always encoded as 16-bit, and this is indeed done for performance reasons. However, there is an option, `variableMapSize` to always use the shortest/preferred encoding for objects serialized as maps as well, but there is a noticeable performance cost (since the keys must be counted prior to serializing them). For floating point numbers, there are also configuration options to control when you want to encode as 32-bit (vs the 64-bit default). I have not yet made any attempt to serialize floating point numbers as 16-bit "Half-Precision Float", as I don't think there is much native support for that in JS, it a unusual encoding format, and I think it would be a bit complicated/slower, but I could look into that (cbor-x can deserialize 16-bit floats though).

**Comment by JonasKruckenberg** [comment]
Oh thanks for the detailed explanation! 
I'm working on a js COSE library at the moment, so I'm happy to take a performance hit with some serializations as long as the result adheres to the "preferred" encoding, so your tips regarding settings is very helpful! 
I agree that there's not much use for 16 bit floats, plus the RFC itself is somewhat ambiguous about floats anyway...

**Comment by kriszyp** [comment]
This should be published in v0.8.3.

**Comment by JonasKruckenberg** [comment]
Woop woop 🥳🥳

**Comment by kdubb** [comment]
@kriszyp Preferred/canonical mode also requires the lexicographical sorting of map keys based on their serialized bytes. Is that also enabled? This is especially important for things like COSE.
