### ISSUE TITLE
Decoding of CBOR encoded float number returns wrong values

### ISSUE THREAD

**Issue by zinke-ct-video** [kriszyp/cbor-x#45]
Hello,

I have the float number 12.75 encoded as [0xF9, 0x4A, 0x60] using the online CBOR encoder [cbor.me](https://cbor.me). Now I want to decode these 3 bytes using cbor-x.

If I run the following code
```JS
import {decode} from "cbor-x";
console.log( decode(new Uint8Array([0xF9, 0x4A, 0x60])) );
```
it returns Infinity instead of the number 12.75. Do you have any explanation for this or could you please fix this?

Thank you very much :)

Edit: I just checked the RFC and it states [here](https://www.rfc-editor.org/rfc/rfc8949#name-preferred-serialization) that always the shortest possible representation should be returned.
There is an example in the RFC: 0xf94580 is also decoded by cbor-x to Infinity instead of 5.5. And encoding 5.5 using cbor-x returns a Uint8Array with 5 bytes instead of 3 bytes as required by the RFC.

**Comment by kriszyp** [comment]
The referenced commits should properly implement float16 support and fix this so that float16 encodings are properly decoded. As far as encoding...

> I just checked the RFC and it states [here](https://www.rfc-editor.org/rfc/rfc8949#name-preferred-serialization) that always the shortest possible representation should be returned.

That is not what the RFC says, the word "should" doesn't even appear in that entire section! It defines what "preferred serialization" means, and some reasons/rationale, but never says you "should" or "must" use it, and even specifically says that the spec does _not_ enforce preferred serialization (nor is required for "deterministic" encoding). And there are also reasons not to use it, namely performance, and in this case, the fact that float-16 is fairly esoteric number format, with very little native or hardware level support for it, and the most likely type not to be supported by other CBOR decoders.

That being said, at some point, I may try to implement support for encoding with float16, but this is more computationally complex and I would need to do some assessments of the performance impact.

Anyway, will publish this update soon.

**Comment by zinke-ct-video** [comment]
Okay, I admit that I have only skimmed the RFC to understand what those 3 bytes mean. Thank's for the clarification :)

And I agree that a performance focused implementation needn't necessarily encode float values to float16. But I think decoding float16 should be possible because otherwise it would be complicated or even impossible to use cbor-x on input data which was encoded with a different encoder that makes use of float16 values.

Thank you for the fast response and fix.
